/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet_clinic;

CREATE TABLE animals (
    id INT PRIMARY KEY     NOT NULL,
    name TEXT    NOT NULL,
    date_of_birth  DATE NOT NULL,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

-- Add species column.
ALTER TABLE animals ADD species CHAR(50);

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name CHAR(50) NOT NULL,
    age  INT
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHAR(25) NOT NULL
);

-- Make sure animals table id is auto-incrementing.
ALTER TABLE animals ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

-- Remove the species column.
ALTER TABLE animals DROP species;

-- Add foreign keys column
ALTER TABLE animals ADD species_id INT REFERENCES species(id);
ALTER TABLE animals ADD owner_id INT REFERENCES owners(id);
 